// Fourfold core - JSON data embedded into the binary (Private/Generated/EmbeddedDataGen.cpp, generated by
// unreal/CoreTests/tools/embed_data.py from Source/FourfoldCore/Data/*.json).
#pragma once

#include <string>
#include <string_view>
#include <vector>

namespace ff {

// Minified JSON text of Data/<name>.json ("moves", "rules", "hooks", "sim", "scenarios", "lab", "move_index");
// empty when unknown.
std::string EmbeddedJson(std::string_view name);
std::vector<std::string> EmbeddedJsonNames();

}  // namespace ff
