#!/usr/bin/env python3
"""Embeds Source/FourfoldCore/Data/*.json (except the test-only golden_matrix.json) into
Source/FourfoldCore/Private/Generated/EmbeddedDataGen.cpp.

Each file is minified (key order and number spelling kept: ints stay ints, floats keep '.'/'e'), split into chunks of
at most 8000 bytes (each chunk one string literal made of adjacent pieces), and concatenated at runtime by
ff::EmbeddedJson(name). Output is deterministic; it is committed so the Mac build needs no Python.

Usage: python3 unreal/CoreTests/tools/embed_data.py [--check]
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MODULE = os.path.normpath(os.path.join(HERE, "..", "..", "Source", "FourfoldCore"))
DATA = os.path.join(MODULE, "Data")
OUT = os.path.join(MODULE, "Private", "Generated", "EmbeddedDataGen.cpp")
FILES = ["moves", "rules", "hooks", "sim", "scenarios", "lab", "move_index"]
CHUNK = 8000
PIECE = 160


def minify(text):
    obj = json.loads(text, parse_float=lambda s: ("__F__", s))
    out = []

    def emit(v):
        if isinstance(v, tuple) and len(v) == 2 and v[0] == "__F__":
            s = v[1]
            if "." not in s and "e" not in s and "E" not in s:
                s += ".0"
            out.append(s)
        elif isinstance(v, dict):
            out.append("{")
            first = True
            for k, x in v.items():
                if not first:
                    out.append(",")
                first = False
                out.append(json.dumps(k, ensure_ascii=True))
                out.append(":")
                emit(x)
            out.append("}")
        elif isinstance(v, list):
            out.append("[")
            for i, x in enumerate(v):
                if i:
                    out.append(",")
                emit(x)
            out.append("]")
        elif isinstance(v, bool):
            out.append("true" if v else "false")
        elif v is None:
            out.append("null")
        elif isinstance(v, int):
            out.append(str(v))
        elif isinstance(v, str):
            out.append(json.dumps(v, ensure_ascii=True))
        else:
            raise TypeError(type(v))

    emit(obj)
    return "".join(out)


def c_escape(s):
    o = []
    for ch in s:
        if ch == "\\":
            o.append("\\\\")
        elif ch == '"':
            o.append('\\"')
        elif ch == "?":
            o.append("\\?")  # never form trigraph-like sequences
        elif 32 <= ord(ch) < 127:
            o.append(ch)
        else:
            o.append("\\x%02x" % ord(ch))
    return "".join(o)


def generate():
    lines = [
        "// GENERATED by unreal/CoreTests/tools/embed_data.py from Source/FourfoldCore/Data/*.json - do not edit.",
        "// Engine-free; part of the FourfoldCore module (no UE headers).",
        '#include "Data/EmbeddedData.h"',
        "",
        "#include <cstring>",
        "",
        "namespace ff {",
        "namespace {",
        "",
    ]
    table = []
    for name in FILES:
        with open(os.path.join(DATA, name + ".json"), "r", encoding="utf-8") as f:
            text = minify(f.read())
        data = text.encode("ascii")
        chunks = [data[i:i + CHUNK].decode("ascii") for i in range(0, len(data), CHUNK)] or [""]
        ident = "kEmbed_" + name
        lines.append("const char* const %s[] = {" % ident)
        for c in chunks:
            pieces = [c[i:i + PIECE] for i in range(0, len(c), PIECE)] or [""]
            lines.append("\t// chunk")
            for p in pieces:
                lines.append('\t"%s"' % c_escape(p))
            lines.append("\t,")
        lines.append("};")
        lines.append("")
        table.append((name, ident, len(chunks), len(data)))
    lines.append("struct EmbedEntry {")
    lines.append("\tconst char* name;")
    lines.append("\tconst char* const* chunks;")
    lines.append("\tint count;")
    lines.append("\tunsigned long bytes;")
    lines.append("};")
    lines.append("")
    lines.append("const EmbedEntry kEmbedTable[] = {")
    for name, ident, n, size in table:
        lines.append('\t{"%s", %s, %d, %dul},' % (name, ident, n, size))
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace")
    lines.append("")
    lines.append("std::string EmbeddedJson(std::string_view name) {")
    lines.append("\tfor (const EmbedEntry& e : kEmbedTable) {")
    lines.append("\t\tif (name != e.name) continue;")
    lines.append("\t\tstd::string out;")
    lines.append("\t\tout.reserve(e.bytes);")
    lines.append("\t\tfor (int i = 0; i < e.count; ++i) out.append(e.chunks[i]);")
    lines.append("\t\treturn out;")
    lines.append("\t}")
    lines.append("\treturn std::string();")
    lines.append("}")
    lines.append("")
    lines.append("std::vector<std::string> EmbeddedJsonNames() {")
    lines.append("\tstd::vector<std::string> out;")
    lines.append("\tfor (const EmbedEntry& e : kEmbedTable) out.emplace_back(e.name);")
    lines.append("\treturn out;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace ff")
    lines.append("")
    return "\n".join(lines)


def main():
    text = generate()
    if "--check" in sys.argv:
        old = open(OUT, "r", encoding="utf-8").read() if os.path.exists(OUT) else ""
        if old != text:
            print("EmbeddedDataGen.cpp is out of date; run unreal/CoreTests/tools/embed_data.py")
            return 1
        print("EmbeddedDataGen.cpp is up to date")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d bytes)" % (OUT, len(text)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
