"""Generates C++ (through Private/Logic/tests/hlsl_shim.h) from the material spec, for the CPU preview renderer
(Private/Logic/tests/fx_preview.cpp): every Custom-node `code` of Content/Python/fourfold/fx/spec.py becomes a C++
function with the same body, plus a per-material dispatch that wires the graph sources exactly like the editor builder
does. The preview therefore runs the very HLSL the materials run (math-wise).

    python3 gen_preview_nodes.py <out header>     (CMake runs it for the ffx_preview target)
"""
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UNREAL = os.path.abspath(os.path.join(HERE, "..", "..", ".."))


def load_spec():
    path = os.path.join(UNREAL, "Content", "Python", "fourfold", "fx", "spec.py")
    s = importlib.util.spec_from_file_location("ff_fx_spec", path)
    m = importlib.util.module_from_spec(s)
    s.loader.exec_module(m)
    return m


SRC_EXPR = {
    "uv0": "in.uv0", "uv1": "in.uv1", "uv2": "in.uv2", "vc": "in.vc", "vca": "in.vca", "time": "in.time",
    "lpos": "in.lpos", "lpos_ps": "in.lpos", "nrm_local": "in.nrmLocal", "nrm_ws": "in.nrmWS", "cam": "in.cam",
    "wpos_cr": "in.wposCR", "ax": "in.ax", "ay": "in.ay", "az": "in.az",
}
BLEND = {"opaque": 0, "alpha_composite": 1, "additive": 2, "translucent": 3}
PROP = {"BaseColor": "base", "EmissiveColor": "emissive", "Normal": "normal", "Roughness": "rough",
        "Specular": "spec", "Metallic": "metal", "Opacity": "opacity"}


def cpp_type(t):
    return {"Texture2D": "const Texture2D&"}.get(t, t)


def main(out_path):
    spec = load_spec()
    common = ["FFCommon", "FFNoise", "FFFlipbook", "FFLighting", "FFFlow", "FFDither"]
    fx = sorted(f[:-4] for f in os.listdir(os.path.join(UNREAL, "Shaders", "FX")) if f.endswith(".ush"))
    L = ["// GENERATED by unreal/Tools/vfx/shader_check/gen_preview_nodes.py from Content/Python/fourfold/fx/spec.py",
         "// Do not edit. Included inside namespace fxs (with `using namespace hlsl;`) by fx_preview.cpp.", ""]
    for c in common:
        L.append(f'#include "{UNREAL}/Shaders/Common/{c}.ush"')
    for f in fx:
        L.append(f'#include "{UNREAL}/Shaders/FX/{f}.ush"')
    L.append("")
    L.append("struct ParamSource {")
    L.append("\tvirtual ~ParamSource() = default;")
    L.append("\tvirtual float S(const char* name, float def) const = 0;")
    L.append("\tvirtual float3 V(const char* name, float3 def) const = 0;")
    L.append("\tvirtual const Texture2D& T(const char* name) const = 0;")
    L.append("};")
    L.append("struct NodeIn {")
    L.append("\tfloat2 uv0, uv1, uv2; float3 vc; float vca = 1.0f; float time = 0.0f;")
    L.append("\tfloat3 lpos, nrmLocal, nrmWS, cam, wposCR, ax, ay, az;")
    L.append("};")
    L.append("struct MatOut {")
    L.append("\tfloat3 base{0.5f, 0.5f, 0.5f}, emissive, normal{0.0f, 0.0f, 1.0f};")
    L.append("\tfloat rough = 0.8f, spec = 0.5f, metal = 0.0f, opacity = 1.0f;")
    L.append("};")
    L.append("struct MatInfo { const char* key; int blend; bool lit; bool twoSided; bool tangentNormal; bool hasWpo; };")
    L.append("")
    keys = list(spec.MATERIALS.keys())
    for key, mat in spec.MATERIALS.items():
        for nid, node in mat["nodes"].items():
            params = []
            for name, src in node["inputs"].items():
                t = spec.source_type(src)
                if t == "Texture2D":
                    params += [f"const Texture2D& {name}", f"const SamplerState& {name}Sampler"]
                elif src.startswith("node:"):
                    params.append(f"{mat['nodes'][src[5:]]['type']} {name}")
                else:
                    params.append(f"{t} {name}")
            for oname, otype in node["outputs"].items():
                params.append(f"{otype}& {oname}")
            L.append(f"inline {node['type']} N_{key}_{nid}({', '.join(params)})")
            L.append("{")
            L += ["\t" + ln for ln in node["code"].splitlines()]
            L.append("}")
            L.append("")

    def args_for(key, mat, nid, node, outs_prefix):
        a = []
        for name, src in node["inputs"].items():
            kind, _, pname = src.partition(":")
            if src in SRC_EXPR:
                a.append(SRC_EXPR[src])
            elif kind == "p":
                a.append(f'ps.S("{pname}", {float(mat["scalars"][pname])}f)')
            elif kind == "v":
                c = mat["vectors"][pname]
                a.append(f'ps.V("{pname}", float3({float(c[0])}f, {float(c[1])}f, {float(c[2])}f))')
            elif kind == "tex":
                a += [f'ps.T("{pname}")', "SamplerState()"]
            elif kind == "nmap":
                a.append("in.nrmWS")
            elif kind == "node":
                a.append(f"v_{src[5:]}")
            else:
                raise SystemExit(f"unknown source {src} in {key}/{nid}")
        for oname in node["outputs"]:
            a.append(f"{outs_prefix}{oname}")
        return ", ".join(a)

    # vertex stage dispatch
    L.append("inline float3 VertexStage(int mat, const NodeIn& in, const ParamSource& ps)")
    L.append("{")
    L.append("\tswitch (mat) {")
    for i, (key, mat) in enumerate(spec.MATERIALS.items()):
        wpo = mat["outputs"].get("WorldPositionOffset")
        if not wpo:
            continue
        node = mat["nodes"][wpo[0]]
        L.append(f"\tcase {i}: return N_{key}_{wpo[0]}({args_for(key, mat, wpo[0], node, 'o_')});")
    L.append("\tdefault: return float3(0.0f, 0.0f, 0.0f);")
    L.append("\t}")
    L.append("}")
    L.append("")
    # pixel stage dispatch
    L.append("inline void PixelStage(int mat, const NodeIn& in, const ParamSource& ps, MatOut& out)")
    L.append("{")
    L.append("\tswitch (mat) {")
    for i, (key, mat) in enumerate(spec.MATERIALS.items()):
        L.append(f"\tcase {i}: {{")
        for nid, node in mat["nodes"].items():
            if node["stage"] != "ps":
                continue
            for oname, otype in node["outputs"].items():
                zero = {"float": "0.0f", "float3": "float3(0.0f, 0.0f, 0.0f)"}[otype]
                L.append(f"\t\t{otype} {nid}_{oname} = {zero};")
            L.append(f"\t\tconst {node['type']} v_{nid} = N_{key}_{nid}({args_for(key, mat, nid, node, nid + '_')});")
        for prop, (nid, oname) in mat["outputs"].items():
            if prop == "WorldPositionOffset":
                continue
            field = PROP[prop]
            L.append(f"\t\tout.{field} = {('v_' + nid) if not oname else (nid + '_' + oname)};")
        for prop, val in mat.get("constants", {}).items():
            L.append(f"\t\tout.{PROP[prop]} = {float(val)}f;")
        L.append("\t\treturn;")
        L.append("\t}")
    L.append("\tdefault: return;")
    L.append("\t}")
    L.append("}")
    L.append("")
    L.append("inline const MatInfo kMatInfo[] = {")
    for key, mat in spec.MATERIALS.items():
        L.append(f'\t{{"{key}", {BLEND[mat["blend"]]}, {str(mat["lit"]).lower()}, {str(mat["two_sided"]).lower()}, '
                 f'{str(mat.get("tangent_normal", True)).lower()}, '
                 f'{str("WorldPositionOffset" in mat["outputs"]).lower()}}},')
    L.append("};")
    L.append(f"inline constexpr int kNumMats = {len(keys)};")
    # the vertex dispatch needs output temporaries for nodes with outputs (none today); declare a guard
    text = "\n".join(L) + "\n"
    if "o_" in text.split("inline float3 VertexStage", 1)[1].split("inline void PixelStage", 1)[0]:
        raise SystemExit("vertex nodes with additional outputs are not supported by the preview generator")
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)


if __name__ == "__main__":
    main(sys.argv[1])
