// GENERATED by Private/Logic/tools/gen_anim_defaults.py from unreal/docs/MARTIAL_ARTS.md - do not edit by hand.
// Built-in clip catalogue + move -> clip map of the native anim runtime (overridden key by key by
// Content/Fourfold/Data/clips.json and anim_map.json).
#include "FFGAnimLibrary.h"

namespace ffg {

void AddBuiltinAnimDefaults(AnimLibrary& lib) {
	lib.AddDefaultClip("a_circle_walk", 96, true, {}, 0.0f);
	lib.AddDefaultClip("a_clap", 18, false, {6}, 0.0f);
	lib.AddDefaultClip("a_dash", 18, false, {8}, 0.0f);
	lib.AddDefaultClip("a_double_palm", 30, false, {12}, 0.0f);
	lib.AddDefaultClip("a_downdraft", 24, false, {10}, 0.0f);
	lib.AddDefaultClip("a_gather", 48, false, {30}, 0.0f);
	lib.AddDefaultClip("a_guard", 96, true, {}, 0.0f);
	lib.AddDefaultClip("a_hurricane", 48, false, {28}, 0.0f);
	lib.AddDefaultClip("a_low_palm", 30, false, {14}, 0.0f);
	lib.AddDefaultClip("a_palm", 22, false, {8}, 0.0f);
	lib.AddDefaultClip("a_pierce", 24, false, {10}, 0.0f);
	lib.AddDefaultClip("a_pluck", 24, false, {10}, 0.0f);
	lib.AddDefaultClip("a_rising_guard", 24, false, {10}, 0.0f);
	lib.AddDefaultClip("a_roar", 36, false, {14}, 0.0f);
	lib.AddDefaultClip("a_spin", 36, false, {18}, 0.0f);
	lib.AddDefaultClip("a_stance", 144, true, {}, 0.0f);
	lib.AddDefaultClip("a_turn_palm", 36, false, {16}, 0.0f);
	lib.AddDefaultClip("a_updraft", 30, false, {14}, 0.0f);
	lib.AddDefaultClip("a_wall_push", 30, false, {12}, 0.0f);
	lib.AddDefaultClip("block_impact", 16, false, {2}, 0.0f);
	lib.AddDefaultClip("c_chain_stomp", 60, false, {12, 24, 36}, 0.0f);
	lib.AddDefaultClip("c_fuse_loop", 72, true, {}, 0.0f);
	lib.AddDefaultClip("c_point", 24, false, {10}, 0.0f);
	lib.AddDefaultClip("c_toss", 20, false, {8}, 0.0f);
	lib.AddDefaultClip("deflect", 22, false, {5}, 0.0f);
	lib.AddDefaultClip("e_burrow", 28, false, {14}, 0.0f);
	lib.AddDefaultClip("e_chain_whirl", 36, false, {14}, 0.0f);
	lib.AddDefaultClip("e_disc_flick", 20, false, {8}, 0.0f);
	lib.AddDefaultClip("e_ground_rise", 30, false, {15}, 0.0f);
	lib.AddDefaultClip("e_ground_slap", 30, false, {14}, 0.0f);
	lib.AddDefaultClip("e_guard", 96, true, {}, 0.0f);
	lib.AddDefaultClip("e_heave", 36, false, {18}, 0.0f);
	lib.AddDefaultClip("e_lift", 24, false, {12}, 0.0f);
	lib.AddDefaultClip("e_lob", 24, false, {12}, 0.0f);
	lib.AddDefaultClip("e_magma_hold", 72, true, {}, 0.0f);
	lib.AddDefaultClip("e_overhead_slam", 36, false, {18}, 0.0f);
	lib.AddDefaultClip("e_pour", 30, false, {16}, 0.0f);
	lib.AddDefaultClip("e_push", 30, false, {10}, 0.0f);
	lib.AddDefaultClip("e_seize_loop", 72, true, {}, 0.0f);
	lib.AddDefaultClip("e_shadowless_kick", 30, false, {12}, 0.0f);
	lib.AddDefaultClip("e_sink", 24, false, {8}, 0.0f);
	lib.AddDefaultClip("e_spatter", 30, false, {12}, 0.0f);
	lib.AddDefaultClip("e_stance", 120, true, {}, 0.0f);
	lib.AddDefaultClip("e_stone_skin", 96, true, {}, 0.0f);
	lib.AddDefaultClip("e_strike", 24, false, {8}, 0.0f);
	lib.AddDefaultClip("e_sweep", 30, false, {13}, 0.0f);
	lib.AddDefaultClip("e_throw", 24, false, {8}, 0.0f);
	lib.AddDefaultClip("e_thrust", 24, false, {12}, 0.0f);
	lib.AddDefaultClip("e_wall", 24, false, {10}, 0.0f);
	lib.AddDefaultClip("evade_back", 28, false, {12}, 0.0f);
	lib.AddDefaultClip("evade_fwd", 28, false, {12}, 0.0f);
	lib.AddDefaultClip("evade_l", 28, false, {12}, 0.0f);
	lib.AddDefaultClip("evade_r", 28, false, {12}, 0.0f);
	lib.AddDefaultClip("f_charge", 48, true, {}, 0.0f);
	lib.AddDefaultClip("f_column", 30, false, {12}, 0.0f);
	lib.AddDefaultClip("f_corona", 36, false, {18}, 0.0f);
	lib.AddDefaultClip("f_crescent_kick", 30, false, {14}, 0.0f);
	lib.AddDefaultClip("f_cross", 24, false, {8}, 0.0f);
	lib.AddDefaultClip("f_dash", 24, false, {8}, 0.0f);
	lib.AddDefaultClip("f_heat_draw", 96, true, {}, 0.0f);
	lib.AddDefaultClip("f_hop", 30, false, {12}, 0.0f);
	lib.AddDefaultClip("f_inferno", 48, false, {26}, 0.0f);
	lib.AddDefaultClip("f_jab", 18, false, {6}, 0.0f);
	lib.AddDefaultClip("f_low_sweep", 36, false, {16}, 0.0f);
	lib.AddDefaultClip("f_needle", 20, false, {8}, 0.0f);
	lib.AddDefaultClip("f_palm_burst", 24, false, {6}, 0.0f);
	lib.AddDefaultClip("f_pour", 30, false, {16}, 0.0f);
	lib.AddDefaultClip("f_snap_kick", 24, false, {10}, 0.0f);
	lib.AddDefaultClip("f_stance", 72, true, {}, 0.0f);
	lib.AddDefaultClip("f_stomp", 24, false, {10}, 0.0f);
	lib.AddDefaultClip("f_thermal_hold", 72, true, {}, 0.0f);
	lib.AddDefaultClip("f_tornado_kick", 48, false, {28}, 0.0f);
	lib.AddDefaultClip("fall", 48, true, {}, 0.0f);
	lib.AddDefaultClip("flight", 72, true, {}, 0.0f);
	lib.AddDefaultClip("getup", 48, false, {}, 0.0f);
	lib.AddDefaultClip("glide", 96, true, {}, 0.0f);
	lib.AddDefaultClip("guard_break", 36, false, {6}, 0.0f);
	lib.AddDefaultClip("hand_crane", 1, false, {}, 0.0f);
	lib.AddDefaultClip("hand_cup", 1, false, {}, 0.0f);
	lib.AddDefaultClip("hand_fist", 1, false, {}, 0.0f);
	lib.AddDefaultClip("hand_oxtongue", 1, false, {}, 0.0f);
	lib.AddDefaultClip("hand_palm", 1, false, {}, 0.0f);
	lib.AddDefaultClip("hand_relaxed", 1, false, {}, 0.0f);
	lib.AddDefaultClip("hand_spread", 1, false, {}, 0.0f);
	lib.AddDefaultClip("hand_sword", 1, false, {}, 0.0f);
	lib.AddDefaultClip("hand_tiger", 1, false, {}, 0.0f);
	lib.AddDefaultClip("hand_willow", 1, false, {}, 0.0f);
	lib.AddDefaultClip("hit_heavy", 36, false, {6}, 0.0f);
	lib.AddDefaultClip("hit_light_back", 22, false, {3}, 0.0f);
	lib.AddDefaultClip("hit_light_front", 22, false, {3}, 0.0f);
	lib.AddDefaultClip("hover", 72, true, {}, 0.0f);
	lib.AddDefaultClip("idle", 120, true, {}, 0.0f);
	lib.AddDefaultClip("jump", 18, false, {10}, 0.0f);
	lib.AddDefaultClip("knockdown", 42, false, {4}, 0.0f);
	lib.AddDefaultClip("l_charge", 96, true, {}, 0.0f);
	lib.AddDefaultClip("l_fan", 30, false, {12}, 0.0f);
	lib.AddDefaultClip("l_ground", 30, false, {14}, 0.0f);
	lib.AddDefaultClip("l_redirect", 36, false, {10, 26}, 0.0f);
	lib.AddDefaultClip("l_release", 20, false, {6}, 0.0f);
	lib.AddDefaultClip("l_skybreak", 36, false, {24}, 0.0f);
	lib.AddDefaultClip("land", 18, false, {4}, 0.0f);
	lib.AddDefaultClip("run", 36, true, {}, 5.5f);
	lib.AddDefaultClip("salute", 60, false, {}, 0.0f);
	lib.AddDefaultClip("skate", 48, true, {}, 0.0f);
	lib.AddDefaultClip("stagger", 30, false, {6}, 0.0f);
	lib.AddDefaultClip("strafe_l", 54, true, {}, 1.1f);
	lib.AddDefaultClip("strafe_r", 54, true, {}, 1.1f);
	lib.AddDefaultClip("surf", 48, true, {}, 0.0f);
	lib.AddDefaultClip("turn_l90", 30, false, {18}, 0.0f);
	lib.AddDefaultClip("turn_r90", 30, false, {18}, 0.0f);
	lib.AddDefaultClip("w_clench", 18, false, {10}, 0.0f);
	lib.AddDefaultClip("w_crane", 30, false, {15}, 0.0f);
	lib.AddDefaultClip("w_draw", 30, false, {22}, 0.0f);
	lib.AddDefaultClip("w_freeze", 24, false, {14}, 0.0f);
	lib.AddDefaultClip("w_ground", 36, false, {18}, 0.0f);
	lib.AddDefaultClip("w_heel_kick", 30, false, {14}, 0.0f);
	lib.AddDefaultClip("w_hold", 96, true, {}, 0.0f);
	lib.AddDefaultClip("w_lash", 30, false, {14}, 0.0f);
	lib.AddDefaultClip("w_maelstrom", 48, false, {24}, 0.0f);
	lib.AddDefaultClip("w_press", 24, false, {10}, 0.0f);
	lib.AddDefaultClip("w_push", 30, false, {12}, 0.0f);
	lib.AddDefaultClip("w_release", 24, false, {8}, 0.0f);
	lib.AddDefaultClip("w_repulse", 28, false, {12}, 0.0f);
	lib.AddDefaultClip("w_shield", 96, true, {}, 0.0f);
	lib.AddDefaultClip("w_shuttle", 30, false, {14}, 0.0f);
	lib.AddDefaultClip("w_single_whip", 30, false, {14}, 0.0f);
	lib.AddDefaultClip("w_snake", 30, false, {14}, 0.0f);
	lib.AddDefaultClip("w_stance", 144, true, {}, 0.0f);
	lib.AddDefaultClip("walk", 54, true, {}, 1.4f);
	lib.AddDefaultClip("walk_back", 54, true, {}, 1.0f);
	lib.AddClipFallback("a_circle_walk", "run");
	lib.AddClipFallback("c_chain_stomp", "f_stomp");
	lib.AddClipFallback("c_toss", "e_disc_flick");
	lib.AddClipFallback("e_spatter", "e_sweep");
	lib.AddClipFallback("f_corona", "f_crescent_kick");
	lib.AddClipFallback("l_fan", "l_release");
	lib.AddClipFallback("w_crane", "w_ground");
	lib.AddClipFallback("w_shuttle", "w_push");
	{
		MoveAnimEntry& m = lib.DefaultMove("aegis_plate");
		m.base.hold = "e_guard";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("afterburn");
		m.base.hold = "run";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("afterglow");
		m.base.hold = "hover";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("air_attack");
		m.base.startup = "a_palm";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
		m.tiers[1].release = "a_double_palm";
		m.tiers[2].release = "a_double_palm";
		m.tiers[3].release = "a_hurricane";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("air_dash");
		m.base.startup = "a_dash";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("air_tech");
		m.base.startup = "a_updraft";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("arc_fan");
		m.base.startup = "l_fan";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("arc_step");
		m.base.startup = "f_dash";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("backdraft");
		m.base.startup = "f_palm_burst";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("blast_jump");
		m.base.startup = "f_hop";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("blue_aegis");
		m.base.hold = "guard";
		m.base.perfect = "deflect";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("blue_furrow");
		m.base.startup = "f_low_sweep";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("blue_needle");
		m.base.startup = "f_needle";
		m.base.hold = "f_charge";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("bramble_lash");
		m.base.startup = "w_lash";
		m.base.hand_l = "crane";
		m.base.hand_r = "crane";
		m.tiers[3].release = "w_maelstrom";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("burr_shot");
		m.base.startup = "w_press";
		m.base.hand_l = "crane";
		m.base.hand_r = "crane";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("canopy");
		m.base.hold = "hover";
		m.base.hand_l = "relaxed";
		m.base.hand_r = "relaxed";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("chain_arc");
		m.base.startup = "e_chain_whirl";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("chain_blasts");
		m.base.startup = "c_chain_stomp";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("cinder_step");
		m.base.startup = "evade_fwd";
		m.base.hand_l = "relaxed";
		m.base.hand_r = "relaxed";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("comet_flame");
		m.base.startup = "f_snap_kick";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("conductors_hand");
		m.base.hold = "l_charge";
		m.base.release = "l_release";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("corona");
		m.base.startup = "f_corona";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("creeping_fog");
		m.base.startup = "w_crane";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("deep_roots");
		m.base.startup = "w_snake";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("dew_fall");
		m.base.startup = "w_snake";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("dune_push");
		m.base.startup = "e_push";
		m.base.hand_l = "tiger";
		m.base.hand_r = "tiger";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("dune_wall");
		m.base.startup = "e_wall";
		m.base.hold = "e_guard";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("earth_attack");
		m.base.startup = "e_lift";
		m.base.release = "e_strike";
		m.base.hand_l = "tiger";
		m.base.hand_r = "fist";
		m.tiers[1].release = "e_heave";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("earth_tech");
		m.base.hold = "e_seize_loop";
		m.base.release = "e_throw";
		m.base.hand_l = "spread";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("ember_clot");
		m.base.startup = "e_lob";
		m.base.hand_l = "cup";
		m.base.hand_r = "cup";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("evade@0");
		m.base.startup = "evade_*";
		m.base.hand_l = "relaxed";
		m.base.hand_r = "relaxed";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("evade@2");
		m.base.startup = "evade_*";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("fire_attack");
		m.base.startup = "f_jab";
		m.base.hold = "f_charge";
		m.base.hand_l = "fist";
		m.base.hand_r = "palm";
		m.tiers[1].release = "f_palm_burst";
		m.tiers[2].release = "f_column";
		m.tiers[3].release = "f_inferno";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("fire_fan");
		m.base.startup = "f_crescent_kick";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
		m.tiers[3].release = "f_tornado_kick";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("fire_line");
		m.base.startup = "f_low_sweep";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("fire_tech");
		m.base.hold = "f_thermal_hold";
		m.base.release = "f_pour";
		m.base.hand_l = "cup";
		m.base.hand_r = "spread";
		m.modes["draw"].hold = "f_heat_draw";
		m.modes["heat"].hold = "f_thermal_hold";
		m.modes["heat"].release = "f_pour";
		m.modes["scorch"].hold = "f_heat_draw";
		m.modes["vent"].startup = "f_palm_burst";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("fireball");
		m.base.startup = "f_snap_kick";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("flame_guard");
		m.base.hold = "guard";
		m.base.perfect = "deflect";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("flare_dash");
		m.base.startup = "evade_*";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("flash_over");
		m.base.startup = "f_palm_burst";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("fog_lance");
		m.base.startup = "w_press";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("fog_walk");
		m.base.hold = "walk";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("freeze_draw");
		m.base.startup = "w_draw";
		m.base.hold = "w_hold";
		m.base.release = "w_release";
		m.base.hand_l = "cup";
		m.base.hand_r = "cup";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("frost_floor");
		m.base.startup = "w_snake";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("frost_shard");
		m.base.startup = "w_freeze";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("fuse");
		m.base.hold = "c_fuse_loop";
		m.base.release = "c_point";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("glacier_shove");
		m.base.startup = "w_heel_kick";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("grit_shot");
		m.base.startup = "e_lift";
		m.base.release = "e_strike";
		m.base.hand_l = "tiger";
		m.base.hand_r = "tiger";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("ground_current");
		m.base.startup = "l_ground";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("ground_heat");
		m.base.startup = "f_stomp";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("grounding");
		m.base.startup = "f_stomp";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("guard@0");
		m.base.startup = "e_wall";
		m.base.hold = "e_guard";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("guard@1");
		m.base.hold = "w_shield";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("guard@3");
		m.base.hold = "a_guard";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("gust_crescent");
		m.base.startup = "a_pierce";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("gust_crosswind");
		m.base.startup = "a_turn_palm";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("gust_downdraft");
		m.base.startup = "a_downdraft";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("gust_dust_line");
		m.base.startup = "a_low_palm";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("gust_grip");
		m.base.startup = "a_pluck";
		m.base.hold = "a_guard";
		m.base.release = "a_palm";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("gust_tailwind");
		m.base.hold = "a_circle_walk";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("gust_wall");
		m.base.startup = "a_wall_push";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("hoarfrost_fan");
		m.base.startup = "w_single_whip";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("ice_glide");
		m.base.startup = "evade_*";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("ice_wall");
		m.base.startup = "w_freeze";
		m.base.hold = "w_shield";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("icicle_volley");
		m.base.startup = "w_press";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("iron_lance");
		m.base.startup = "e_thrust";
		m.base.hand_l = "crane";
		m.base.hand_r = "crane";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("iron_stance");
		m.base.hold = "e_stone_skin";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("kiln");
		m.base.hold = "f_heat_draw";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("lattice_roll");
		m.base.startup = "w_shuttle";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("lava_lash");
		m.base.startup = "e_chain_whirl";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("lava_wade");
		m.base.hold = "walk";
		m.base.hand_l = "relaxed";
		m.base.hand_r = "relaxed";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("lightning");
		m.base.startup = "l_release";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
		m.tiers[3].release = "l_skybreak";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("living_lattice");
		m.base.hold = "w_shield";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("lodestone_grip");
		m.base.hold = "e_seize_loop";
		m.base.release = "e_throw";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("lodestone_line");
		m.base.startup = "e_ground_slap";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("magma_curtain");
		m.base.startup = "e_wall";
		m.base.hold = "e_guard";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("magma_hold");
		m.base.hold = "e_magma_hold";
		m.base.release = "e_pour";
		m.base.hand_l = "cup";
		m.base.hand_r = "cup";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("magma_surge");
		m.base.startup = "e_pour";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("magnet_glide");
		m.base.startup = "a_dash";
		m.base.hand_l = "relaxed";
		m.base.hand_r = "relaxed";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("melt_pit");
		m.base.startup = "e_sink";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("mist_step");
		m.base.startup = "w_repulse";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("overcharge");
		m.base.hold = "run";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("plate_rush");
		m.base.startup = "e_disc_flick";
		m.base.hand_l = "crane";
		m.base.hand_r = "crane";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("pop");
		m.base.startup = "f_jab";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
		m.tiers[1].release = "c_point";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("pour");
		m.base.startup = "f_pour";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("quicksand");
		m.base.startup = "e_sink";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("rail_arc");
		m.base.startup = "l_release";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("ram_wall");
		m.base.startup = "e_push";
		m.base.hand_l = "tiger";
		m.base.hand_r = "tiger";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("razor_disc");
		m.base.startup = "e_disc_flick";
		m.base.hand_l = "crane";
		m.base.hand_r = "crane";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("reactive_blast");
		m.base.hold = "guard";
		m.base.perfect = "deflect";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("rime_path");
		m.base.startup = "w_ground";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("riptide_step");
		m.base.startup = "w_repulse";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("rising_fangs");
		m.base.startup = "e_ground_rise";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("rocket_hop");
		m.base.startup = "f_hop";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("rod_plant");
		m.base.startup = "e_overhead_slam";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("root_snare");
		m.base.startup = "w_ground";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("rubble_fan");
		m.base.startup = "e_sweep";
		m.base.hand_l = "crane";
		m.base.hand_r = "crane";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sand_ride");
		m.base.hold = "surf";
		m.base.hand_l = "relaxed";
		m.base.hand_r = "relaxed";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sand_surf");
		m.base.startup = "e_burrow";
		m.base.hand_l = "relaxed";
		m.base.hand_r = "relaxed";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sand_surge");
		m.base.startup = "e_ground_slap";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sandblast");
		m.base.startup = "e_thrust";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sandform");
		m.base.hold = "e_seize_loop";
		m.base.release = "e_throw";
		m.base.hand_l = "cup";
		m.base.hand_r = "cup";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("scald_puff");
		m.base.startup = "w_push";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("scatter_charges");
		m.base.startup = "c_toss";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("shimmer_step");
		m.base.startup = "f_dash";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("shockwave");
		m.base.startup = "f_palm_burst";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("skate");
		m.base.hold = "skate";
		m.base.hand_l = "relaxed";
		m.base.hand_r = "relaxed";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("slag_wave");
		m.base.startup = "e_pour";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("slick");
		m.base.startup = "w_snake";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("smelter");
		m.base.hold = "f_heat_draw";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("smother_blast");
		m.base.startup = "f_hop";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sound_barrier");
		m.base.hold = "a_guard";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sound_boom_step");
		m.base.startup = "a_dash";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sound_clap");
		m.base.startup = "a_clap";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
		m.tiers[1].release = "a_roar";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sound_echo_ring");
		m.base.startup = "a_spin";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sound_flight");
		m.base.startup = "a_updraft";
		m.base.hold = "flight";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sound_hover");
		m.base.hold = "hover";
		m.base.hand_l = "relaxed";
		m.base.hand_r = "relaxed";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sound_lance");
		m.base.startup = "a_pierce";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sound_ping");
		m.base.startup = "f_stomp";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sound_thunder_step");
		m.base.startup = "a_dash";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("sound_tremor");
		m.base.startup = "f_stomp";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("spark");
		m.base.startup = "f_jab";
		m.base.hold = "l_charge";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
		m.tiers[1].release = "l_release";
		m.tiers[3].release = "l_skybreak";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("spark_mine");
		m.base.startup = "c_toss";
		m.base.hand_l = "crane";
		m.base.hand_r = "crane";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("spatter_arc");
		m.base.startup = "e_spatter";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("spear_stone");
		m.base.startup = "e_thrust";
		m.base.hand_l = "tiger";
		m.base.hand_r = "tiger";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("spray_fan");
		m.base.startup = "w_single_whip";
		m.base.hand_l = "willow";
		m.base.hand_r = "crane";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("static_burst");
		m.base.startup = "f_palm_burst";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("static_ward");
		m.base.hold = "guard";
		m.base.perfect = "l_redirect";
		m.base.hand_l = "sword";
		m.base.hand_r = "sword";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("steam_blast");
		m.base.startup = "w_push";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("steam_screen");
		m.base.hold = "w_shield";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("stone_skin");
		m.base.hold = "e_stone_skin";
		m.base.hand_l = "fist";
		m.base.hand_r = "fist";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("surge_orb");
		m.base.startup = "w_push";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("swallow");
		m.base.startup = "e_sink";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("thicket_fan");
		m.base.startup = "w_single_whip";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("tidal_rush");
		m.base.startup = "w_ground";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vacuum_anchor");
		m.base.startup = "a_downdraft";
		m.base.hold = "e_stone_skin";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vacuum_arc");
		m.base.startup = "a_turn_palm";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vacuum_bubble");
		m.base.hold = "a_guard";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vacuum_hop");
		m.base.startup = "a_updraft";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vacuum_mine");
		m.base.startup = "a_low_palm";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vacuum_palm");
		m.base.startup = "a_palm";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
		m.tiers[1].release = "a_double_palm";
		m.tiers[2].release = "a_hurricane";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vacuum_slipstream");
		m.base.hold = "a_circle_walk";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vacuum_suction");
		m.base.startup = "a_pluck";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vacuum_wave");
		m.base.startup = "a_wall_push";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vacuum_well");
		m.base.startup = "a_gather";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vapor_draw");
		m.base.startup = "w_draw";
		m.base.hold = "w_hold";
		m.base.release = "w_release";
		m.base.hand_l = "cup";
		m.base.hand_r = "cup";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("veil");
		m.base.startup = "w_single_whip";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("veil_of_grit");
		m.base.startup = "e_sweep";
		m.base.hand_l = "crane";
		m.base.hand_r = "crane";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vent");
		m.base.startup = "f_palm_burst";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vine_swing");
		m.base.startup = "evade_*";
		m.base.hand_l = "crane";
		m.base.hand_r = "crane";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vinegrip");
		m.base.startup = "w_draw";
		m.base.hold = "w_hold";
		m.base.release = "w_release";
		m.base.hand_l = "spread";
		m.base.hand_r = "spread";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vortex_eddy");
		m.base.startup = "a_spin";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vortex_eye");
		m.base.startup = "a_gather";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vortex_funnel");
		m.base.startup = "a_low_palm";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vortex_funnel_down");
		m.base.startup = "a_downdraft";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vortex_spin_step");
		m.base.startup = "a_spin";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vortex_spiral");
		m.base.startup = "a_pierce";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vortex_twister");
		m.base.startup = "a_spin";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vortex_unleash");
		m.base.startup = "a_wall_push";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vortex_wall");
		m.base.startup = "a_rising_guard";
		m.base.hold = "a_guard";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("vortex_whirl");
		m.base.hold = "hover";
		m.base.hand_l = "oxtongue";
		m.base.hand_r = "oxtongue";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("water_attack");
		m.base.startup = "w_lash";
		m.base.hand_l = "willow";
		m.base.hand_r = "fist";
		m.tiers[1].release = "w_freeze";
		m.tiers[2].release = "w_push";
		m.tiers[3].release = "w_maelstrom";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("water_bullet");
		m.base.startup = "w_press";
		m.base.hand_l = "palm";
		m.base.hand_r = "palm";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("water_tech");
		m.base.startup = "w_draw";
		m.base.hold = "w_hold";
		m.base.release = "w_release";
		m.base.hand_l = "cup";
		m.base.hand_r = "cup";
	}
	{
		MoveAnimEntry& m = lib.DefaultMove("wave_ride");
		m.base.hold = "surf";
		m.base.hand_l = "willow";
		m.base.hand_r = "willow";
	}
}

}  // namespace ffg
