"""Fourfold audio import (stream `world_audio`): the synthesised WAVs become SoundWave assets, with looping flags, memory
behaviour and (optionally) sound classes.

    import fourfold.audio as fa; fa.build_all(force=False)   -> report dict {"created", "skipped", "failed", "notes"}

Sources (generated by unreal/Tools/audio, committed): unreal/SourceArt/Audio/SFX/<name>.wav and
unreal/SourceArt/Audio/Ambience/<name>.wav; the list, the loop flags and the asset paths come from
Content/Fourfold/Data/sfx_manifest.json (which the runtime module FourfoldAudio reads as well). Produces:
    /Game/Fourfold/Audio/SFX/S_<name>        /Game/Fourfold/Audio/Ambience/S_<name>        (USoundWave, mono 48 kHz)
    /Game/Fourfold/Audio/Classes/SC_{Master,SFX,UI,Ambience}   (optional USoundClass assets; skipped when the API is missing)
Idempotent: existing assets are kept (their loop / memory settings are re-checked); force=True re-imports everything.
Never raises: failures are collected in the report. APIs used (with sources): unreal/docs/audio/API_NOTES.md.
"""
import json
import os
import traceback

import unreal

AUDIO_ROOT = "/Game/Fourfold/Audio"
CLASS_DIR = AUDIO_ROOT + "/Classes"
EAL = unreal.EditorAssetLibrary
BATCH = 40


def _log(msg):
    unreal.log(f"[Fourfold][audio] {msg}")


def _warn(msg):
    unreal.log_warning(f"[Fourfold][audio] {msg}")


def _err(msg):
    unreal.log_error(f"[Fourfold][audio] {msg}")


def _paths():
    proj = unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir())
    art = os.path.join(proj, "SourceArt", "Audio")
    manifest = os.path.join(proj, "Content", "Fourfold", "Data", "sfx_manifest.json")
    return art, manifest


def _load_sounds(art, manifest_path, report):
    """{name: {"asset": "/Game/...", "loop": bool, "bus": str, "src": wav path}} from the manifest (fallback: scan the folders)."""
    sounds = {}
    try:
        with open(manifest_path, encoding="utf-8") as f:
            data = json.load(f)
        for name, s in data.get("sounds", {}).items():
            folder = "Ambience" if "/Ambience/" in s.get("asset", "") else "SFX"
            sounds[name] = {"asset": s["asset"], "loop": bool(s.get("loop", False)), "bus": s.get("bus", "sfx"),
                            "src": os.path.join(art, folder, name + ".wav")}
    except Exception as e:  # noqa: BLE001
        report["notes"].append(f"sfx_manifest.json not readable ({e}); importing every WAV found under SourceArt/Audio")
        for folder in ("SFX", "Ambience"):
            d = os.path.join(art, folder)
            if not os.path.isdir(d):
                continue
            for fn in sorted(os.listdir(d)):
                if fn.endswith(".wav"):
                    name = fn[:-4]
                    sounds[name] = {"asset": f"{AUDIO_ROOT}/{folder}/S_{name}", "loop": False,
                                    "bus": "ambience" if folder == "Ambience" else "sfx", "src": os.path.join(d, fn)}
    return sounds


def _split(asset_path):
    """'/Game/A/B/S_x' -> ('/Game/A/B', 'S_x')"""
    folder, _, name = asset_path.rpartition("/")
    return folder, name


def _enum(enum_cls_name, member):
    """unreal.<EnumClass>.<MEMBER> or None (the member names follow UE's UPPER_SNAKE conversion; verified in API_NOTES)."""
    try:
        return getattr(getattr(unreal, enum_cls_name), member)
    except Exception:  # noqa: BLE001
        return None


def _set(obj, prop, value, report, quiet=False):
    if value is None:
        return False
    try:
        obj.set_editor_property(prop, value)
        return True
    except Exception as e:  # noqa: BLE001
        if not quiet:
            report["notes"].append(f"could not set {prop} on {obj.get_name()}: {e}")
        return False


def _save(asset):
    try:
        EAL.save_loaded_asset(asset, False)
    except Exception:  # noqa: BLE001
        EAL.save_loaded_asset(asset)


# ------------------------------------------------------------------------------------------------ sound classes (optional)
def build_classes(report, force):
    """SC_Master > SC_SFX / SC_UI / SC_Ambience. Returns {name: asset or None}. Skipped quietly when the API is missing."""
    classes = {}
    try:
        factory_cls = getattr(unreal, "SoundClassFactory", None)
        sound_class = getattr(unreal, "SoundClass", None)
        if factory_cls is None or sound_class is None:
            report["notes"].append("unreal.SoundClassFactory / SoundClass not available: sound classes skipped")
            return classes
        tools = unreal.AssetToolsHelpers.get_asset_tools()
        for name in ("SC_Master", "SC_SFX", "SC_UI", "SC_Ambience"):
            path = f"{CLASS_DIR}/{name}"
            if EAL.does_asset_exist(path) and not force:
                classes[name] = unreal.load_asset(path)
                report["skipped"].append(path)
                continue
            asset = tools.create_asset(name, CLASS_DIR, sound_class, factory_cls())
            if asset is None:
                report["notes"].append(f"could not create {path}")
                continue
            classes[name] = asset
            report["created"].append(path)
        master = classes.get("SC_Master")
        if master is not None:
            for name in ("SC_SFX", "SC_UI", "SC_Ambience"):
                child = classes.get(name)
                if child is not None:
                    try:
                        child_props = child.get_editor_property("properties")
                        _ = child_props  # per-class volume stays 1.0: the game mixes volumes itself (FourfoldAudio)
                        master_children = list(master.get_editor_property("child_classes"))
                        if child not in master_children:
                            master_children.append(child)
                            master.set_editor_property("child_classes", master_children)
                    except Exception as e:  # noqa: BLE001
                        report["notes"].append(f"could not parent {name} under SC_Master: {e}")
        for a in classes.values():
            _save(a)
    except Exception as e:  # noqa: BLE001
        report["notes"].append(f"sound classes skipped: {e}")
    return classes


# ------------------------------------------------------------------------------------------------ waves
def _apply_wave_settings(wave, info, classes, report):
    """Looping flag, sound group, memory behaviour, compression, class. Returns True when anything changed."""
    changed = False
    try:
        cur = bool(wave.get_editor_property("looping"))
    except Exception:  # noqa: BLE001
        cur = None
    if cur is None or cur != info["loop"]:
        changed |= _set(wave, "looping", info["loop"], report)
    bus = info["bus"]
    group = _enum("SoundGroup", "SOUNDGROUP_UI" if bus == "ui" else "SOUNDGROUP_EFFECTS")
    if group is not None:
        changed |= _set(wave, "sound_group", group, report, quiet=True)
    # short one-shots keep their first chunk in memory (no hitch on the first play); loops / beds are primed
    beh = _enum("SoundWaveLoadingBehavior", "PRIME_ON_LOAD" if (info["loop"] or bus == "ambience") else "RETAIN_ON_LOAD")
    if beh is not None:
        changed |= _set(wave, "loading_behavior", beh, report, quiet=True)
    changed |= _set(wave, "compression_quality", 50 if (info["loop"] or bus == "ambience") else 70, report, quiet=True)
    cls = classes.get({"ui": "SC_UI", "ambience": "SC_Ambience"}.get(bus, "SC_SFX"))
    if cls is not None:
        changed |= _set(wave, "sound_class_object", cls, report, quiet=True)
    return changed


def import_waves(sounds, classes, force, report):
    pending = []
    for name, info in sounds.items():
        dst = info["asset"]
        folder, asset_name = _split(dst)
        if not os.path.exists(info["src"]):
            report["failed"].append({"item": dst, "error": f"missing source {info['src']} (run unreal/Tools/audio/render_audio.py)"})
            continue
        if EAL.does_asset_exist(dst) and not force:
            wave = unreal.load_asset(dst)
            if wave is not None and _apply_wave_settings(wave, info, classes, report):
                _save(wave)
            report["skipped"].append(dst)
            continue
        t = unreal.AssetImportTask()
        t.set_editor_property("filename", info["src"])
        t.set_editor_property("destination_path", folder)
        t.set_editor_property("destination_name", asset_name)
        t.set_editor_property("replace_existing", True)
        t.set_editor_property("automated", True)
        t.set_editor_property("save", False)
        pending.append((t, info, dst))
    tools = unreal.AssetToolsHelpers.get_asset_tools()
    for i in range(0, len(pending), BATCH):
        chunk = pending[i:i + BATCH]
        try:
            tools.import_asset_tasks([t for t, _, _ in chunk])
        except Exception as e:  # noqa: BLE001
            for _t, _info, dst in chunk:
                report["failed"].append({"item": dst, "error": f"import_asset_tasks raised: {e}"})
            continue
        for _t, info, dst in chunk:
            wave = unreal.load_asset(dst)
            if wave is None:
                report["failed"].append({"item": dst, "error": "SoundWave import produced nothing"})
                continue
            _apply_wave_settings(wave, info, classes, report)
            _save(wave)
            report["created"].append(dst)


def build_all(force=False):
    report = {"created": [], "skipped": [], "failed": [], "notes": []}
    try:
        art, manifest = _paths()
        sounds = _load_sounds(art, manifest, report)
        if not sounds:
            report["failed"].append({"item": "audio", "error": f"no sounds found (manifest {manifest}, sources {art})"})
            return report
        _log(f"{len(sounds)} sounds ({sum(1 for s in sounds.values() if s['loop'])} loops), force={force}")
        classes = build_classes(report, force)
        import_waves(sounds, classes, force, report)
        _log(f"done: created {len(report['created'])}, skipped {len(report['skipped'])}, failed {len(report['failed'])}")
    except Exception as e:  # noqa: BLE001
        _err(f"audio build failed: {e}\n{traceback.format_exc()}")
        report["failed"].append({"item": "audio", "error": str(e)})
    return report
