"""Texture import for the courtyard (PNG -> Texture2D) with the right compression / colour space per kind.

Files: unreal/SourceArt/Environment/Textures/T_Env_*.png (generated by Tools/world/gen_env_textures*.py).
Kinds (from the file name): *_BC sRGB colour; *_N tangent normal map (DirectX, no flip); *_ORM masks (R AO, G roughness, B metal);
T_Env_Noise / Clouds / ArenaMask linear masks (arena mask clamps); T_Env_WaterN normal; T_Env_Foliage_BC / Banners_BC colour with alpha."""
import os

import unreal

from . import common as C

KIND = {
    "BC": "color",
    "N": "normal",
    "ORM": "masks",
}
SPECIAL = {
    "T_Env_WaterN": "normal",
    "T_Env_Noise": "masks",
    "T_Env_Clouds": "masks",
    "T_Env_ArenaMask": "mask_clamp",
    "T_Env_Foliage_BC": "color_alpha",
    "T_Env_Banners_BC": "color_alpha",
}


def kind_of(name):
    if name in SPECIAL:
        return SPECIAL[name]
    return KIND.get(name.rsplit("_", 1)[-1], "color")


def apply_settings(tex, name, report):
    kind = kind_of(name)
    TC = C.enum("TextureCompressionSettings", "TC_DEFAULT")
    P = C.set_prop
    if kind in ("color", "color_alpha"):
        P(tex, "srgb", True, report)
        P(tex, "compression_settings", C.enum("TextureCompressionSettings", "TC_DEFAULT"), report)
        if kind == "color_alpha":
            P(tex, "compress_without_alpha", False, report, quiet=True)
            P(tex, "mip_gen_settings", C.enum("TextureMipGenSettings", "TMGS_FROM_TEXTURE_GROUP"), report, quiet=True)
    elif kind == "normal":
        P(tex, "srgb", False, report)
        P(tex, "compression_settings", C.enum("TextureCompressionSettings", "TC_NORMALMAP"), report)
        P(tex, "flip_green_channel", False, report, quiet=True)          # the generator already writes DirectX (green down)
        P(tex, "lod_group", C.enum("TextureGroup", "TEXTUREGROUP_WORLD_NORMAL_MAP"), report, quiet=True)
    else:
        P(tex, "srgb", False, report)
        P(tex, "compression_settings", C.enum("TextureCompressionSettings", "TC_MASKS", "TC_DEFAULT"), report)
        if kind == "mask_clamp":
            P(tex, "address_x", C.enum("TextureAddress", "TA_CLAMP"), report, quiet=True)
            P(tex, "address_y", C.enum("TextureAddress", "TA_CLAMP"), report, quiet=True)
            P(tex, "mip_gen_settings", C.enum("TextureMipGenSettings", "TMGS_NO_MIPMAPS"), report, quiet=True)
    if kind in ("color", "color_alpha", "masks", "mask_clamp"):
        P(tex, "lod_group", C.enum("TextureGroup", "TEXTUREGROUP_WORLD"), report, quiet=True)
    # mobile: keep a maximum size of 2048 (all sources are 1024)
    P(tex, "max_texture_size", 2048, report, quiet=True)


def import_all(force, report):
    """Imports every PNG of SourceArt/Environment/Textures into /Game/Fourfold/Env/Textures.  Returns {name: asset path}."""
    paths = C.project_paths()
    src_dir = paths["textures"]
    out = {}
    if not os.path.isdir(src_dir):
        report["failed"].append({"item": "textures", "error": f"missing folder {src_dir} (run Tools/world/gen_env_textures*.py)"})
        return out
    C.make_dirs(C.ENV_ROOT, C.TEX_DIR)
    tasks = []
    for fn in sorted(os.listdir(src_dir)):
        if not fn.lower().endswith(".png"):
            continue
        name = fn[:-4]
        dst = f"{C.TEX_DIR}/{name}"
        out[name] = dst
        if C.asset_exists(dst) and not force:
            report["skipped"].append(dst)
            continue
        t = unreal.AssetImportTask()
        t.set_editor_property("filename", os.path.join(src_dir, fn))
        t.set_editor_property("destination_path", C.TEX_DIR)
        t.set_editor_property("destination_name", name)
        t.set_editor_property("replace_existing", True)
        t.set_editor_property("automated", True)
        t.set_editor_property("save", False)
        tasks.append((t, name, dst))
    if tasks:
        try:
            unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([t for t, _, _ in tasks])
        except Exception as e:  # noqa: BLE001
            report["failed"].append({"item": "texture import", "error": str(e)})
            return out
    for _t, name, dst in tasks:
        tex = unreal.load_asset(dst)
        if tex is None:
            report["failed"].append({"item": dst, "error": "texture import produced nothing"})
            continue
        apply_settings(tex, name, report)
        C.save_asset(tex)
        report["created"].append(dst)
    # existing textures keep their settings (they were applied when created); re-apply cheaply on force only
    return out


def tex(name):
    path = f"{C.TEX_DIR}/{name}"
    return unreal.load_asset(path) if C.asset_exists(path) else None
