// Fourfold core - open world ("roam"): the authored valley the combat bubble travels through.
// Added 2026-10-09 (open-world stream, additive; Unreal-only - the Godot build has no open world).
//
// World space: metres, +Y up, x / z as in sim space. The 60 Hz sim never runs in world space: it runs in a local
// bubble (an arena window, half size kRoamHalfSize) whose origin - sim (0,0,0) - sits at Session::BubbleOrigin() in
// world space. Outside fights the bubble re-centres on the player; during an encounter it stays put and the window is
// the arena. Every re-centre emits app_recenter {dx, dy, dz} (local positions moved by -d, the origin by +d).
//
// Data: Content/Fourfold/Data/openworld/world.json + the float32 little-endian heightfield it names
// (generated by unreal/Tools/openworld/gen_world.py; never hand-edited).
#pragma once

#include "ff/Config.h"
#include "ff/Math.h"

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

namespace ff {

inline constexpr double kRoamHalfSize = 20.0;   // the bubble is a 40 x 40 m window

struct WorldBox {               // world-space solid (rock outcrops, ruin walls, temple steps)
	Vec3 min, max;
	std::string kind;           // wall | ledge | pillar
	std::string surface;        // stone
	std::string name;
};

struct WorldRect {              // x / z rectangle in world space
	Vec2 min, max;
};

struct EncounterSite {          // a fighter waiting in the world; engages when the player comes close
	std::string id;
	std::string name;
	std::string region;         // water | earth | fire | air | hub
	Vec3 pos;                   // world
	float facing = 0.0f;
	int element = 0;
	int sub = -1;               // -1 = any sub-element of that element
	std::string preset = "adept";   // novice | adept | master
	float aggro_radius = 9.0f;
};

struct Shrine {                 // respawn point after a lost fight
	std::string id;
	std::string name;
	Vec3 pos;
};

struct FOURFOLDCORE_API WorldDef {
	// Heightfield: nx * nz samples, row-major (z outer); sample (i, k) sits at (x0 + i * cell, z0 + k * cell).
	int nx = 0;
	int nz = 0;
	double x0 = 0.0;
	double z0 = 0.0;
	double cell = 2.0;
	std::vector<float> heights;
	double water_level = -1.0e9;    // lake surface (world y): terrain below it is water
	double wade_depth = 0.85;       // a fighter stands at most this deep (the floor clamps up to water_level - wade_depth)
	std::vector<WorldBox> solids;
	std::vector<WorldRect> metal;   // exposed ore plates (earth / metal techniques)
	std::vector<EncounterSite> sites;
	std::vector<Shrine> shrines;
	Vec3 player_spawn;
	float spawn_facing = 0.0f;

	double SizeX() const { return nx > 1 ? (nx - 1) * cell : 0.0; }
	double SizeZ() const { return nz > 1 ? (nz - 1) * cell : 0.0; }
	// Bilinear terrain height, clamped to the grid edge (0 when the grid is empty).
	double HeightAt(double x, double z) const;
	// Standing floor: terrain, raised to water_level - wade_depth in deep water.
	double FloorAt(double x, double z) const;
	bool IsWater(double x, double z) const { return HeightAt(x, z) < water_level; }
	bool OnMetal(double x, double z) const;

	// Parses world.json; `heights` is the float32 blob it names (nx * nz * 4 bytes). False + error on bad data.
	static bool Parse(std::string_view json, const void* heights, size_t bytes, WorldDef& out, std::string* error = nullptr);
};

// Header-inline so the presentation logic islands (camera, IK, FX ground) link without the core library.
inline double WorldDef::HeightAt(double x, double z) const {
	if (nx < 2 || nz < 2 || heights.size() < static_cast<size_t>(nx) * static_cast<size_t>(nz)) return 0.0;
	double fx = (x - x0) / cell;
	double fz = (z - z0) / cell;
	fx = fx < 0.0 ? 0.0 : (fx > nx - 1 ? nx - 1 : fx);
	fz = fz < 0.0 ? 0.0 : (fz > nz - 1 ? nz - 1 : fz);
	int i = static_cast<int>(fx);
	int k = static_cast<int>(fz);
	if (i > nx - 2) i = nx - 2;
	if (k > nz - 2) k = nz - 2;
	const double tx = fx - i;
	const double tz = fz - k;
	const size_t row = static_cast<size_t>(nx);
	const size_t b = static_cast<size_t>(k) * row + static_cast<size_t>(i);
	const double h00 = heights[b];
	const double h10 = heights[b + 1];
	const double h01 = heights[b + row];
	const double h11 = heights[b + row + 1];
	return (h00 * (1.0 - tx) + h10 * tx) * (1.0 - tz) + (h01 * (1.0 - tx) + h11 * tx) * tz;
}

inline double WorldDef::FloorAt(double x, double z) const {
	const double h = HeightAt(x, z);
	if (h < water_level) {
		const double wade = water_level - wade_depth;
		return h > wade ? h : wade;
	}
	return h;
}

inline bool WorldDef::OnMetal(double x, double z) const {
	for (const WorldRect& r : metal)
		if (x > r.min.x && x < r.max.x && z > r.min.y && z < r.max.y) return true;
	return false;
}

struct RoamOptions {
	std::string kit;                // "" = saved progression kit; "all" = every technique (testing)
	std::string autoplay;           // "" | "duel" | "soak" (as ScenarioOptions)
	int player_element = -1;
	bool encounters = true;         // false: free roaming without fights
};

struct EncounterView {
	std::string id;
	std::string name;
	std::string region;
	Vec3 pos;                       // world
	int element = 0;
	std::string state;              // waiting | engaged | defeated
};

struct RoamView {
	bool active = false;            // a roam session is loaded
	double origin_x = 0.0, origin_y = 0.0, origin_z = 0.0;   // world position of sim (0,0,0)
	int engaged = -1;               // index into sites, -1 when roaming
	std::vector<EncounterView> sites;
	std::string region;             // region of the nearest site (HUD / music)
};

}  // namespace ff
