// FourfoldAudio logic island - sfx_manifest.json model + parser (engine-free: no Unreal headers).
// The manifest (Content/Fourfold/Data/sfx_manifest.json, generated by unreal/Tools/audio/build_manifest.py) holds the sounds
// (asset path, gain, voices, loop, bus, attenuation class), the event -> sound rules, the state-driven loop rules, footsteps,
// ambience, UI cue names and the mix settings. The rule language is documented in unreal/Tools/audio/event_rules.py.
#pragma once

#include "ff/Value.h"

#include <cstdint>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace ffa {

enum class Op : uint8_t { Eq, Ne, Gt, Gte, Lt, Lte, In, Nin, Has, Nhas, Truthy, Falsy };

struct Cond {
	std::string field;
	Op op = Op::Eq;
	ff::Value arg;
};

struct GainMap {
	bool valid = false;
	std::string field;
	float in_lo = 0.0f, in_hi = 1.0f, db_lo = 0.0f, db_hi = 0.0f;
};

// What a play resolves to: a literal sound, "tmpl_{field}" (fields substituted), a round-robin list, or a table lookup.
struct SoundRef {
	enum class Kind : uint8_t { None, Literal, Template, List, Table };
	Kind kind = Kind::None;
	std::string text;                 // Literal / Template
	std::vector<std::string> list;    // List
	std::string table;                // Table
	std::vector<std::string> key;     // Table: fields joined with '_'
	std::string def;                  // Table: default sound ("" = none)
};

struct Play {
	SoundRef sound;
	std::vector<std::string> at;      // position sources, first available wins; empty = 2D
	float gain_db = 0.0f;
	float pitch = 1.0f;
	float chance = 1.0f;
	std::string limit;                // named limiter ("" = none)
	GainMap gain_map;
	bool two_d = false;
	float delay_s = 0.0f;
};

struct Rule {
	std::string id;
	std::vector<Cond> when;
	std::vector<Play> play;
	bool stop = false;
};

struct SoundDef {
	std::string name;
	std::string asset;                // /Game/Fourfold/Audio/SFX/S_<name>
	std::string category;             // impact | element | ui | ambience | loop
	std::string attenuation;          // near | mid | far | feel | 2d
	std::string bus;                  // sfx | ui | ambience
	std::string family;
	float gain_db = 0.0f;
	float pitch_var = 0.0f;
	float duration_s = 0.0f;
	int max_voices = 2;
	int priority = 2;
	bool loop = false;
	bool stinger = false;
};

struct LimiterDef {
	float gap_s = 0.0f;
	std::string per;                  // "" | "actor"
};

struct AttenDef {
	float inner_cm = 1000.0f;
	float max_cm = 4500.0f;
	float db_at_max = -24.0f;
};

struct LoopRule {                      // loops.bodies / loops.actors
	std::string id;
	std::vector<Cond> when;
	std::string sound;
	float gain_db = 0.0f;
	bool zone = false;                 // slow zone fades
	std::string at;                    // body | chest | feet
};

struct EventLoopRule {                 // loops.events: refreshed by events, expires by itself
	std::string event;
	std::vector<Cond> when;
	std::string sound;
	std::vector<std::string> key;      // fields joined with '_' after the first element (a prefix)
	float hold_s = 0.3f;
	float gain_db = 0.0f;
	bool zone = false;
	std::string at;                    // actor | body
};

struct StepsDef {
	float min_speed = 0.8f;
	float cadence_base = 1.2f;
	float cadence_per_speed = 0.45f;
	float gain_lo = -1.5f, gain_hi = 0.5f;
	float speed_in_lo = 0.8f, speed_in_hi = 5.5f, speed_db_lo = -5.0f, speed_db_hi = 0.0f;
	float pitch_var = 0.04f;
	std::string def = "stone";
	std::unordered_map<std::string, std::vector<std::string>> surfaces;
	std::unordered_map<std::string, std::string> exact;
	std::vector<std::pair<std::string, std::string>> contains;
	int cloth_every = 3;
	std::vector<std::string> cloth_sounds;
};

struct BedDef {
	std::string sound;
	float gain_db = 0.0f;
};

struct AccentDef {
	std::vector<std::string> sounds;
	float min_gap_s = 10.0f, max_gap_s = 30.0f, gain_db = 0.0f, pitch_var = 0.0f;
};

struct FadeDef {
	float body_in = 90.0f, body_out = 60.0f, zone_in = 30.0f, zone_out = 24.0f, floor_db = -40.0f;
};

struct DuckDef {
	std::string bus = "ambience";
	float db = -4.0f, attack_s = 0.04f, hold_s = 0.5f, release_s = 0.9f;
	std::vector<std::string> triggers;
};

struct MixDef {
	int global_voices = 28;
	int loop_voices = 14;
	float steal_fade_s = 0.03f;
	float bus_gain_db[3] = {0.0f, 0.0f, -4.0f};        // sfx, ui, ambience
	FadeDef fade;
	DuckDef duck;
	std::unordered_map<std::string, LimiterDef> limiters;
	std::unordered_map<std::string, AttenDef> attenuation;
};

struct Manifest {
	std::unordered_map<std::string, SoundDef> sounds;
	std::unordered_map<std::string, ff::Dict> tables;                 // table name -> (key -> sound | [sounds])
	std::unordered_map<std::string, std::vector<Rule>> events;
	std::vector<LoopRule> body_loops;
	std::vector<LoopRule> actor_loops;
	std::vector<EventLoopRule> event_loops;
	StepsDef steps;
	std::vector<BedDef> beds;
	std::vector<AccentDef> accents;
	float ambience_fade_in_s = 2.5f;
	std::unordered_map<std::string, std::string> ui;                  // OnUiCue name -> sound
	MixDef mix;

	// Parses the JSON text. Returns false (and fills `error`) when the schema marker is missing or the text is malformed.
	bool Parse(std::string_view text, std::string* error = nullptr);
	const SoundDef* Find(const std::string& name) const;
	int BusIndex(const std::string& bus) const;                        // sfx 0, ui 1, ambience 2 (unknown -> 0)
	int CountEventRules() const;
};

}  // namespace ffa
