class_name ArenaView
extends Node3D
## Builds the visible combat laboratory from ArenaMap (single source of truth), plus light and
## environment: PBR-textured flagstones / masonry / deck plates / pool tile (res://assets/textures,
## generated by tools/textures/gen_env_textures.py), alpha-blended pool water, baked contact-AO,
## warm late-day lighting, boundary dressing (ArenaProps) and distant scenery (ArenaScenery).
##
## Quality tiers (set_quality): 0 = single texture sample per set, no real lights / probe, flat water;
## 1 = anti-tiled textures, shadows, glow, full dressing; 2 = + lantern lights, reflection probe,
## detailed water ripples / bubbles, longer shadow distance.

const SHADER_DIR := "res://presentation/shaders/"
const TEX_DIR := "res://assets/textures/"
const AO_RES := 128
const AO_RECT := Rect2(-17.0, -17.0, 34.0, 34.0)

static var _ao_cache: Dictionary = {}

var arena: ArenaMap
var sun: DirectionalLight3D
var env: WorldEnvironment
var probe: ReflectionProbe
var props: ArenaProps
var scenery: ArenaScenery
var _quality := 1
var _mats: Dictionary = {}        # shared surface materials by shader name
var _tiered: Array[ShaderMaterial] = []


func build(a: ArenaMap, quality: int = 1) -> void:
	arena = a
	_quality = quality
	for c in get_children():
		c.queue_free()
	_mats.clear()
	_tiered.clear()
	_build_lighting()
	_build_floor()
	_build_solids()
	_build_pool()
	_build_metal()
	_build_dressing()
	_build_props()
	_build_scenery()
	set_quality(quality)


func set_quality(q: int) -> void:
	_quality = q
	if sun:
		sun.shadow_enabled = q >= 1
		sun.directional_shadow_max_distance = 28.0 if q >= 2 else 20.0
	for m in _tiered:
		m.set_shader_parameter("anti_tile", q >= 1)
	var water: ShaderMaterial = _mats.get("pool_water")
	if water:
		water.set_shader_parameter("detail", q >= 2)
	if probe:
		probe.visible = q >= 2
	if props:
		props.set_quality(q)
	if scenery:
		scenery.set_quality(q)


## 0 dry .. 1 soaked, for every arena surface of this view (stone, walls, deck plates).
func set_wetness(w: float) -> void:
	for n in ["arena_ground", "ledge_stone", "metal_plate"]:
		var m: ShaderMaterial = _mats.get(n)
		if m:
			m.set_shader_parameter("wetness", clampf(w, 0.0, 1.0))


# --------------------------------------------------------------------------- materials
func _tex(nm: String) -> Texture2D:
	var p := TEX_DIR + nm + ".png"
	if ResourceLoader.exists(p):
		return load(p) as Texture2D
	return null


## One shared ShaderMaterial per shader (all arena surfaces of a look share it, so wetness and the
## quality tier switch every mesh at once).  Falls back to a StandardMaterial3D if the shader is missing.
func _mat(shader_name: String, fallback: Color, rough: float = 0.85, metal: float = 0.0) -> Material:
	var path := SHADER_DIR + shader_name + ".gdshader"
	if not ResourceLoader.exists(path):
		var m := StandardMaterial3D.new()
		m.albedo_color = fallback
		m.roughness = rough
		m.metallic = metal
		return m
	if _mats.has(shader_name):
		return _mats[shader_name]
	# Arena looks are shared through VfxMaterials so VfxMaterials.set_arena_wetness() drives them too.
	var sm: ShaderMaterial = VfxMaterials.shared(shader_name)
	match shader_name:
		"arena_ground":
			_set_set(sm, "albedo_tex", "normal_tex", "orm_tex", "flagstone")
			sm.set_shader_parameter("ao_map", _bake_ao())
			sm.set_shader_parameter("ao_rect", Vector4(AO_RECT.position.x, AO_RECT.position.y, AO_RECT.size.x, AO_RECT.size.y))
			_tiered.append(sm)
		"ledge_stone":
			_set_set(sm, "wall_albedo", "wall_normal", "wall_orm", "wall")
			_set_set(sm, "cap_albedo", "cap_normal", "cap_orm", "ledge_cap")
			_tiered.append(sm)
		"metal_plate":
			_set_set(sm, "albedo_tex", "normal_tex", "orm_tex", "metal_plate")
			sm.set_shader_parameter("ao_map", _bake_ao())
			sm.set_shader_parameter("ao_rect", Vector4(AO_RECT.position.x, AO_RECT.position.y, AO_RECT.size.x, AO_RECT.size.y))
		"pool_basin":
			_set_set(sm, "albedo_tex", "normal_tex", "orm_tex", "pool_tile")
			sm.set_shader_parameter("water_y", arena.pool_level)
	_mats[shader_name] = sm
	return sm


func _set_set(sm: ShaderMaterial, a: String, n: String, o: String, set_name: String) -> void:
	sm.set_shader_parameter(a, _tex(set_name + "_albedo"))
	sm.set_shader_parameter(n, _tex(set_name + "_normal"))
	sm.set_shader_parameter(o, _tex(set_name + "_orm"))


## Baked contact ambient-occlusion over the floor (world XZ -> L8): soft darkening where solids meet
## the ground.  Analytic from ArenaMap's solids, so any arena layout gets it; cached per layout.
func _bake_ao() -> Texture2D:
	var key := ""
	for s in arena.solids:
		key += "%s%s;" % [s.min, s.max]
	if _ao_cache.has(key):
		return _ao_cache[key]
	var bytes := PackedByteArray()
	bytes.resize(AO_RES * AO_RES)
	var step := AO_RECT.size.x / AO_RES
	for j in AO_RES:
		var z := AO_RECT.position.y + (j + 0.5) * step
		for i in AO_RES:
			var x := AO_RECT.position.x + (i + 0.5) * step
			var ao := 1.0
			for s in arena.solids:
				var mn: Vector3 = s.min
				var mx: Vector3 = s.max
				var dx := maxf(maxf(mn.x - x, x - mx.x), 0.0)
				var dz := maxf(maxf(mn.z - z, z - mx.z), 0.0)
				var d := sqrt(dx * dx + dz * dz)
				var hf := clampf(mx.y / 1.4, 0.25, 1.0)
				var r := 0.55 + 0.9 * hf
				if d < r and d > 0.0:
					var t := 1.0 - smoothstep(0.0, r, d)
					ao *= 1.0 - 0.62 * hf * t * t
			bytes[j * AO_RES + i] = int(clampf(ao, 0.0, 1.0) * 255.0)
	var img := Image.create_from_data(AO_RES, AO_RES, false, Image.FORMAT_L8, bytes)
	var tex := ImageTexture.create_from_image(img)
	_ao_cache[key] = tex
	return tex


# --------------------------------------------------------------------------- lighting
func _build_lighting() -> void:
	# Late-day key light: warm, low enough for readable contact shadows, cool sky fill.
	sun = DirectionalLight3D.new()
	sun.name = "Sun"
	sun.rotation_degrees = Vector3(-34, -128, 0)
	sun.light_color = Color(1.0, 0.84, 0.66)
	sun.light_energy = 1.75
	sun.shadow_enabled = _quality >= 1
	sun.shadow_bias = 0.03
	sun.shadow_normal_bias = 1.0
	sun.shadow_blur = 1.2
	sun.directional_shadow_mode = DirectionalLight3D.SHADOW_PARALLEL_2_SPLITS
	sun.directional_shadow_max_distance = 26.0
	add_child(sun)
	env = WorldEnvironment.new()
	env.name = "Env"
	var e := Environment.new()
	var sky := Sky.new()
	var ps := ProceduralSkyMaterial.new()
	ps.sky_top_color = Color(0.24, 0.38, 0.6)
	ps.sky_horizon_color = Color(0.9, 0.72, 0.56)
	ps.sky_curve = 0.14
	ps.ground_bottom_color = Color(0.17, 0.15, 0.13)
	ps.ground_horizon_color = Color(0.74, 0.62, 0.5)
	ps.sun_angle_max = 22.0
	ps.sun_curve = 0.1
	sky.sky_material = ps
	e.background_mode = Environment.BG_SKY
	e.sky = sky
	e.ambient_light_source = Environment.AMBIENT_SOURCE_SKY
	e.ambient_light_energy = 0.62
	e.reflected_light_source = Environment.REFLECTION_SOURCE_SKY
	e.tonemap_mode = Environment.TONE_MAPPER_AGX
	e.tonemap_white = 8.0
	e.tonemap_exposure = 1.05
	e.glow_enabled = _quality >= 1
	e.glow_intensity = 0.45
	e.glow_bloom = 0.03
	e.glow_hdr_threshold = 1.1
	e.fog_enabled = true
	e.fog_light_color = Color(0.82, 0.7, 0.58)
	e.fog_density = 0.0045
	e.fog_sky_affect = 0.3
	e.fog_aerial_perspective = 0.35
	e.adjustment_enabled = true
	e.adjustment_contrast = 1.07
	e.adjustment_saturation = 0.98
	env.environment = e
	add_child(env)
	# One-shot local reflection capture: walls / sky in the pool water, metal deck and wet stone.
	probe = ReflectionProbe.new()
	probe.name = "ArenaProbe"
	probe.position = Vector3(0, 3.0, 0)
	probe.size = Vector3(2.0 * arena.half_size, 12.0, 2.0 * arena.half_size)
	probe.origin_offset = Vector3(0, 0.0, 0)
	probe.box_projection = true
	probe.update_mode = ReflectionProbe.UPDATE_ONCE
	probe.intensity = 0.8
	probe.max_distance = 0.0
	probe.ambient_mode = ReflectionProbe.AMBIENT_DISABLED   # reflections only; ambient stays the sky's
	add_child(probe)


func _box(mn: Vector3, mx: Vector3, mat: Material, nm: String, shadows := true) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	var bm := BoxMesh.new()
	bm.size = mx - mn
	mi.mesh = bm
	mi.position = (mn + mx) * 0.5
	mi.material_override = mat
	mi.name = nm
	if not shadows:
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	add_child(mi)
	return mi


# --------------------------------------------------------------------------- geometry
func _build_floor() -> void:
	var h := arena.half_size
	var mat := _mat("arena_ground", Color(0.56, 0.54, 0.5))
	# Floor tiles around the pool (the pool is a sunken basin).
	var p0 := arena.pool_min
	var p1 := arena.pool_max
	var rects := [
		Rect2(-h, -h, 2 * h, p0.y + h),                 # north of pool
		Rect2(-h, p1.y, 2 * h, h - p1.y),               # south of pool
		Rect2(-h, p0.y, p0.x + h, p1.y - p0.y),         # west strip
		Rect2(p1.x, p0.y, h - p1.x, p1.y - p0.y),       # east strip
	]
	for r in rects:
		if r.size.x <= 0.01 or r.size.y <= 0.01:
			continue
		_box(Vector3(r.position.x, -0.5, r.position.y), Vector3(r.end.x, 0.0, r.end.y), mat, "floor", false)


func _build_solids() -> void:
	var stone := _mat("ledge_stone", Color(0.55, 0.52, 0.47))
	for s in arena.solids:
		_box(s.min, s.max, stone, s.name)


func _build_pool() -> void:
	var p0 := arena.pool_min
	var p1 := arena.pool_max
	var basin := _mat("pool_basin", Color(0.2, 0.45, 0.47))
	var fy := arena.pool_floor
	_box(Vector3(p0.x, fy - 0.3, p0.y), Vector3(p1.x, fy, p1.y), basin, "pool_floor", false)
	# Tile lining on the four basin walls (inside the pool footprint, flush with the floor boxes).
	var t := 0.03
	_box(Vector3(p0.x, fy, p0.y), Vector3(p1.x, 0.0, p0.y + t), basin, "pool_lining_n", false)
	_box(Vector3(p0.x, fy, p1.y - t), Vector3(p1.x, 0.0, p1.y), basin, "pool_lining_s", false)
	_box(Vector3(p0.x, fy, p0.y), Vector3(p0.x + t, 0.0, p1.y), basin, "pool_lining_w", false)
	_box(Vector3(p1.x - t, fy, p0.y), Vector3(p1.x, 0.0, p1.y), basin, "pool_lining_e", false)
	var water := MeshInstance3D.new()
	var pm := PlaneMesh.new()
	pm.size = Vector2(p1.x - p0.x, p1.y - p0.y)
	water.mesh = pm
	water.position = Vector3((p0.x + p1.x) * 0.5, arena.pool_level, (p0.y + p1.y) * 0.5)
	var wm := _mat("pool_water", Color(0.14, 0.32, 0.36, 0.78), 0.08)
	if wm is ShaderMaterial:
		(wm as ShaderMaterial).set_shader_parameter("half_extent", pm.size * 0.5)
		(wm as ShaderMaterial).set_shader_parameter("corner_radius", 0.02)
		(wm as ShaderMaterial).set_shader_parameter("depth_range", 1.6)
	elif wm is StandardMaterial3D:
		(wm as StandardMaterial3D).transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
		(wm as StandardMaterial3D).albedo_color = Color(0.14, 0.32, 0.36, 0.78)
		(wm as StandardMaterial3D).metallic_specular = 0.8
	water.material_override = wm
	water.name = "pool_water"
	water.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	add_child(water)
	# Low coping stones around the pool edge (visual only, flush with the floor).
	var coping := _mat("ledge_stone", Color(0.62, 0.59, 0.54))
	var c := 0.25
	_box(Vector3(p0.x - c, -0.02, p0.y - c), Vector3(p1.x + c, 0.03, p0.y), coping, "coping_n", false)
	_box(Vector3(p0.x - c, -0.02, p1.y), Vector3(p1.x + c, 0.03, p1.y + c), coping, "coping_s", false)
	_box(Vector3(p0.x - c, -0.02, p0.y), Vector3(p0.x, 0.03, p1.y), coping, "coping_w", false)
	_box(Vector3(p1.x, -0.02, p0.y), Vector3(p1.x + c, 0.03, p1.y), coping, "coping_e", false)


func _build_metal() -> void:
	var m0 := arena.metal_min
	var m1 := arena.metal_max
	var mat := _mat("metal_plate", Color(0.32, 0.33, 0.35), 0.4, 0.85)
	_box(Vector3(m0.x, -0.02, m0.y), Vector3(m1.x, arena.metal_top, m1.y), mat, "metal_plate", false)


func _build_dressing() -> void:
	# Start circles for both fighters: bronze inlay rings set flush in the flagstones.
	var ring_mat := StandardMaterial3D.new()
	ring_mat.albedo_color = Color(0.62, 0.46, 0.24)
	ring_mat.metallic = 0.8
	ring_mat.roughness = 0.38
	for p in [arena.player_spawn, arena.opponent_spawn]:
		var mi := MeshInstance3D.new()
		var tm := TorusMesh.new()
		tm.inner_radius = 0.95
		tm.outer_radius = 1.03
		tm.rings = 48
		mi.mesh = tm
		mi.scale = Vector3(1, 0.02, 1)
		mi.position = p + Vector3(0, 0.005, 0)
		mi.material_override = ring_mat
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		add_child(mi)


func _build_props() -> void:
	props = ArenaProps.new()
	props.name = "Props"
	add_child(props)
	props.build(arena, _mat("ledge_stone", Color(0.6, 0.57, 0.52)), _quality)


func _build_scenery() -> void:
	scenery = ArenaScenery.new()
	scenery.name = "Scenery"
	add_child(scenery)
	scenery.build(arena, _quality)
